import { type NextPage } from "next";
import Head from "next/head";

import { NavBar } from "../components";

const HomePage: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="h-16 bg-slate-800">
        <NavBar />
      </div>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-br from-blue-600 to-blue-900 ">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Fake <span className="text-blue-400">Twitter</span> App
          </h1>
        </div>
      </main>
    </>
  );
};

export default HomePage;
